mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.26:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
server:
  name: MQTT_SERVER_DEMO #服务编码
  version: 1.0.0 #服务版本
  port: 58005 #服务占用web端口
spring:
  application:
    name: yytd-mqtt-demo
logging:
  level:
    root: info